name: "download go"

on: push

jobs:
    go_job:
        runs-on: ubuntu-latest
        steps:
        - name: install golang
          uses: actions/setup-go@v4

        - name: display version
          run: go version
    
