name: "first work flow"

on: push

jobs:
    build_job:
        runs-on: ubuntu-latest
        steps:
        - name: checkout repo
          uses: actions/checkout@v4

        - name: welcome message
          run : echo "this is the first action"
        
        - name: list the file in this repo 
          run: ls
        
        - name: read file
          run: cat README.md

        - name: list and read 
          run: |
            echo "here i want to read and list files"
            ls -a
            cat README.md
            echo "hello world" > hello.txt

        - name: upload hello file
          uses: actions/upload-artifact@v4
          with:
            name: hello-text-file
            path: hello.txt
        
        - name: Set up Go
          uses: actions/setup-go@v4
          with:
              go-version: '1.22.2'

        - name: check go version
          run: go version

    testing_job:
        needs: build_job
        runs-on: ubuntu-latest
        steps:
        - name: testing
          run: echo "running test"

        - name: download hello text file
          uses: actions/download-artifact@v4
          with:
            name: hello-text-file
        
        - name: read file
          run: cat hello.txt
        


    deploy_job:
        needs: [testing_job]
        runs-on: ubuntu-latest
        steps:
        - name: testing
          run: echo "running test 1"

    


            